### ISSUE TITLE
Highlighted links on the homepage are getting overlaped. (UI/UX)

### ISSUE THREAD

**Issue by thisispratt** [fluid-project/floeproject.org#114] opened 2020-02-29 15:29 UTC
## Decreasing the line spacing (0.7/0.8) is causing the highlighted links on the homepage to overlap.
=>Above mentioned problem is evident in mobile devices as well as desktops.
=>Setting the contrast as yellow even worsens the problem. (class = "fl-theme-by" on body).
 
### To reproduce
Steps to reproduce the behavior
1. Go to https://floeproject.org
2. Click on show preferences on the top.
3. Change the line spacing to 0.7.
4. See this error.

## Expected Behavior
The highlighted links on the homepage should not overlap.

### 1. iPhone 6/7/8 plus [Chrome dev tools simulator]
![image](https://user-images.githubusercontent.com/40731031/75609908-ae5c5300-5b32-11ea-8779-16e3ee90ece1.png)

### 2. iPhone 6/7/8 plus [Chrome dev tools simulator]
![image](https://user-images.githubusercontent.com/40731031/75610001-786b9e80-5b33-11ea-956b-4defc2a7a404.png)

### 3. Desktop [OS: Windows10, Google Chrome: version 80.0]
![image](https://user-images.githubusercontent.com/40731031/75610056-f92a9a80-5b33-11ea-90a7-e7dbdfb497c7.png)

## Solution proposed
=> Background-color(#FFCB00) on links should be removed. Instead, we can use the text-decoration to highlight the links and that too with the same color(#FFCB00).
This would solve this problem in all the available size displays including (iPad, iPhones, Desktops, Laptops, etc.)

## Alternative solutions considered
=> Changing the opacity of the highlighted links.

### Are you working on this issue (Yes/No)?
Yes

**Comment by sachin10101998** [comment] 2020-02-29 15:41
Already reported in #108

**Comment by sachin10101998** [comment] 2020-02-29 15:48
Duplicate of #108

**Comment by thisispratt** [comment] 2020-02-29 16:21
haha.. That's not well documented.

**Comment by sachin10101998** [comment] 2020-02-29 16:42
@thisispratt The issue can be solved without all the design changes though. Look at this. 
1) Line Spacing: 0.7
![Screenshot from 2020-02-29 22-02-19](https://user-images.githubusercontent.com/34926285/75611363-e6b65e00-5b3f-11ea-9d9b-47013b253d14.png)

2) Line Spacing: 1.3
![Screenshot from 2020-02-29 22-07-01](https://user-images.githubusercontent.com/34926285/75611373-f6ce3d80-5b3f-11ea-98b7-bc336d1ec605.png)

**Comment by thisispratt** [comment] 2020-02-29 17:15
@sachin10101998 how ?

**Comment by sachin10101998** [comment] 2020-02-29 17:29
@thisispratt transform.

**Comment by sachin10101998** [comment] 2020-02-29 17:42
@jhung, @jobara  views?

**Comment by aashimgarg** [comment] 2020-02-29 18:26
Duplicate of #108 !

**Comment by thisispratt** [comment] 2020-02-29 19:35
> @thisispratt scale or transform according to need.
@sachin10101998 So you are suggesting to decrease the size via scale property but that wouldn't go by the definition of design for all.
By using the scale property the size of the text will also decrease while the user only intended to decrease the line-spacing. 
I don't think that this would be a good design practice.

**Comment by thisispratt** [comment] 2020-02-29 19:49
@aashimgarg You didn't document the issue as required by the organization(neither did you gave any explanation about it) even after being asked out by @sachin10101998 you didn't do any changes neither did you propose to solve this issue and now you are talking here and editing your issue (#108 ). Things don't work this way.

**Comment by sachin10101998** [comment] 2020-02-29 19:50
@thisispratt  I am not changing the size of the text with changing line spacing. I fixed the scale of links in one place. Quoting @jobara 

> The purpose of adjusting the line-height is less about setting an absolute value and more about <b>adjusting the presentation of the content to something that suits your needs and preferences. It's unlikely that you'd want to shrink the line-height to a point where the text overlaps.</b> However, if the default styling is to have the text wide apart then you may want to tighten it up. That being said, we want good defaults, so the "1" case should not look stretched.

![Peek 2020-03-01 01-15](https://user-images.githubusercontent.com/34926285/75614038-491c5800-5b5a-11ea-91b3-087a5ce43167.gif)

**Comment by sachin10101998** [comment] 2020-02-29 19:53
@thisispratt  As far as design is concerned, I enquired about this from @jhung. Quoting his reply from mailing list:

> For now we aim to keep the same design with some minor fixes and tweaks. The work of this project is primarily focused on the backend of the sites. If there is time, moving to a more modern CSS framework would be desirable but not a requirement.

**Comment by aashimgarg** [comment] 2020-02-29 19:55
@sachin10101998 i think you added margin properties to this as it clearly shows you have increased the line space!

**Comment by thisispratt** [comment] 2020-02-29 19:57
@sachin10101998  You aren't assigned to work on this issue? or are you?

**Comment by sachin10101998** [comment] 2020-02-29 20:04
@aashimgarg, I neither added margin properties nor increased line spacing. 
@thisispratt, I am not working on this issue. I just suggested an alternative way of solving it. We can discuss issues and come to the best solution by discussion only.

**Comment by thisispratt** [comment] 2020-02-29 20:06
@sachin10101998 Awesome work then, btw have you tested your scaling on multiple mobile devices. Isn't it affecting the font-size?

**Comment by sachin10101998** [comment] 2020-02-29 20:25
@thisispratt , yeah, it's working for all device sizes. 
Font-size doesn't look affected because I approximately balanced the font-weight with font-size. 
1) 

![hhh](https://user-images.githubusercontent.com/34926285/75614462-f2654d00-5b5e-11ea-905a-6449d92cf289.gif)

2) For iPhone 6/7/8

![Screenshot from 2020-03-01 01-53-03](https://user-images.githubusercontent.com/34926285/75614512-89caa000-5b5f-11ea-84ff-d8fb204daabc.png)

**Comment by thisispratt** [comment] 2020-02-29 20:27
@sachin10101998 Nice, I got your point.😂✌

**Comment by sachin10101998** [comment] 2020-02-29 20:30
@thisispratt , you should work on a prototype of your proposed solution too though. It would be easier to compare the different alternatives available. The same goes for @aashimgarg, since he pointed this out first.

**Comment by thisispratt** [comment] 2020-02-29 20:42
@sachin10101998 Should I wait for the approval to work on this issue by someone from the community?

**Comment by thisispratt** [comment] 2020-03-02 07:07
> @thisispratt , yeah, it's working for all device sizes.
.
.
.
> P.S. If I were to write proper code for it, shouldn't I send a PR myself? ;)

@sachin10101998 So you did🤣. 😒

**Comment by sachin10101998** [comment] 2020-03-02 11:59
@thisispratt , I was working on a separate issue. This one got fixed on its own.

**Comment by thisispratt** [comment] 2020-03-02 12:45
@sachin10101998 No problem bro, it can happen with anyone.✌

**Comment by jobara** [comment] 2020-03-03 13:59
@sachin10101998, @aashimgarg, and @thisispratt, thank you for having a discussion about the issue and talking through different points together. Remember that comments, questions, critiques and etc should always be done in a respectful manner. Working in open source is not about competing for the best solution, but about collaborating together to arrive at it.

It's best to continue a discussion on the original issue, rather than filing a new one to propose an alternate solution or expand on the issue. 

As you can see from your discussion there may be multiple ways of addressing the same problem. It is best to discuss these possible alternatives, trade-offs, pros/cons to arrive at a possible solution. it's also okay to add code snippets and working examples in the issue. For example, you may have mocked up something on [codepen](https://codepen.io), [jsfiddle](https://jsfiddle.net), or similar to illustrate possible solutions. 

The use of images and other media is also helpful, but please remember that not everyone viewing this issue may be able to perceive those images (e.g. vision impairment, bandwidth issues, content filtering etc.) so please always make sure to sufficiently describe in text what the image/media is illustrating.

**Closed** 2020-03-03 21:16 UTC
Labels: duplicate
