### ISSUE TITLE
Typesetting Links.

### ISSUE THREAD

**Issue by aashimgarg** [fluid-project/floeproject.org#98] opened 2020-02-22 18:31 UTC
When the cursor is over the links the padding is not present which.

By giving the padding to the link we can get better UI at various places in the webpage.

Example links in the navbar.
Before
![Screenshot from 2020-02-27 19-12-30](https://user-images.githubusercontent.com/55639487/75450936-af0bb280-5995-11ea-90bc-c4bc652deaa8.png)

After
![Screenshot from 2020-02-27 19-16-16](https://user-images.githubusercontent.com/55639487/75450976-c0ed5580-5995-11ea-8a49-e3daa85f43dd.png)

**Comment by jobara** [comment] 2020-02-27 13:13
@aashimgarg can you please provide more information about what the issue is. Steps to reproduce, screen shots, details on why this is an issue and what would help to improve it should be included in the description where possible.

**Comment by aashimgarg** [comment] 2020-02-27 13:49
@jobara i mentioned it.

**Comment by jobara** [comment] 2020-02-27 13:55
@jhung could you please weigh in on this issue and related PR.

**Comment by greatislander** [comment] 2020-09-23 12:03
I'm closing this as we are currently beginning a redesign process which will look at this among other improvements. Thanks for your suggestion!

**Closed by greatislander** 2020-09-23 12:03 UTC
Labels: enhancement, question
