### ISSUE TITLE
image overlap when text size is adjusted to 0.5.

### ISSUE THREAD

**Issue by Chaitanyassr** [fluid-project/floeproject.org#105] opened 2020-02-24 16:09 UTC
## Describe the bug
image overlap when text size is adjusted to 0.5.

### To reproduce
1. click on preference
2. adjust the text size to 0.5
3. See error

### Expected behavior
Image should not overlap with text

## Screenshots
![Screenshot (164)](https://user-images.githubusercontent.com/30374226/75169155-1505f900-574e-11ea-9230-07ff3e20e28a.png)

 - Browser [e.g. chrome]

**Comment by aashimgarg** [comment] 2020-02-24 16:31
Can i work on this issue @Chaitanyassr ?

**Comment by karanb1** [comment] 2020-02-24 23:46
I am working on this issue, @jhung can you help me with this?

**Comment by jhung** [comment] 2020-02-25 13:28
@Chaitanyassr thank you for finding this bug and providing the needed details for us to understand the problem. 👍 

Before starting on a pull request, can someone help investigate the cause of the issue and explain a possible solution?

**Comment by karanb1** [comment] 2020-02-26 09:21
A probable cause can be that the text is responding to the change in size but the images are not responding to that. 
I think putting the text and the image in different divs and defining the image in terms of percentage can solve this issue.

**Comment by sachin10101998** [comment] 2020-02-26 11:08
Interesting Info: The bug is system dependent. On reducing the text size to 0.5, instead of going over the images on the home page, the right column ext and images move on top of the left column images and text. Sample screenshots are attached below. 
1)
![Screenshot from 2020-02-26 16-00-20](https://user-images.githubusercontent.com/34926285/75336538-58c54380-58b1-11ea-8e2d-a410e7d3a0d9.png)
2)
![Screenshot from 2020-02-26 16-02-22](https://user-images.githubusercontent.com/34926285/75336577-67135f80-58b1-11ea-86cf-725d381baf2f.png)

**Comment by sachin10101998** [comment] 2020-03-03 04:01
@jhung the issue is being caused by the fact that the div containing the figure and the parent div container has different width values which are defined in pixels. the div containing the figure as background had dimensions bigger than the parent container. Fixing the div container classes and using percentage values for width and setting the max-width property will solve all the issues. 
Screenshots:

1) 

![Screenshot from 2020-03-03 09-27-29](https://user-images.githubusercontent.com/34926285/75741753-9141a300-5d31-11ea-9861-7f0f537dd8b0.png)

2)

![Screenshot from 2020-03-03 09-27-08](https://user-images.githubusercontent.com/34926285/75741777-a0c0ec00-5d31-11ea-8bdd-8950ac90aec5.png)

**Comment by greatislander** [comment] 2020-09-23 12:10
I'm closing this as we are currently beginning a redesign process which will address this among other improvements. Thanks for reporting it!

**Closed by greatislander** 2020-09-23 12:10 UTC
Labels: bug
