### ISSUE TITLE
Using cursor as pointer in resource page

### ISSUE THREAD

**Issue by samagragupta** [fluid-project/floeproject.org#147] opened 2020-03-19 05:57 UTC
When clicked on the resources the cursor should be a pointer.

**Comment by sachin10101998** [comment] 2020-03-19 09:12
Duplicate of #100

**Comment by Shikhar15606** [comment] 2020-08-13 16:35
Working On the Issue

**Comment by Amulya-coder** [comment] 2020-08-28 13:45
Hi I want to work on this issue #179

**Closed** 2020-09-23 12:04 UTC
Labels: duplicate
