### ISSUE TITLE
There is no spacing before and after the footer tag.

### ISSUE THREAD

**Issue by aashimgarg** [fluid-project/floeproject.org#95] opened 2020-02-22 14:13 UTC
There is no spacing before and after the footer tag and it doesnt look good.

**Comment by jobara** [comment] 2020-02-24 14:45
@aashimgarg could you please provide some more information about this? For example, a link to the code or a code snippet, screen shot, steps to reproduce, browsers and platforms that are affected.

**Comment by aashimgarg** [comment] 2020-02-27 13:57
Before -

![Screenshot from 2020-02-27 19-24-12](https://user-images.githubusercontent.com/55639487/75451671-f5154600-5996-11ea-8143-6e42b0097cc6.png)

After -
![Screenshot from 2020-02-27 19-25-12](https://user-images.githubusercontent.com/55639487/75451778-1aa24f80-5997-11ea-8a18-c694e4ebf6b7.png)

@jobara

**Comment by jobara** [comment] 2020-02-27 13:59
@aashimgarg I'm not sure what I'm looking for in these images. Could you please describe what the key differences are. This will help when comparing the images, and also provide some information for someone who is not able to perceive the images.

**Comment by aashimgarg** [comment] 2020-02-27 14:07
![IMG_20200227_193447](https://user-images.githubusercontent.com/55639487/75452504-6e616880-5998-11ea-89a4-4e8f2f304ba0.png)

As there is no space before and after the footer tag , i have added the space before and after the tag.

**Comment by aashimgarg** [comment] 2020-02-27 14:09
![IMG_20200227_193447](https://user-images.githubusercontent.com/55639487/75452504-6e616880-5998-11ea-89a4-4e8f2f304ba0.png)

@jobara as there is no space before and after the footer tag , i have added the space before and after the tag.

**Comment by jobara** [comment] 2020-02-27 14:28
@aashimgarg from what I understand, this was intentional. Maybe @jhung can clarify.

**Comment by aashimgarg** [comment] 2020-02-27 15:55
ohk @jobara . Take a look at https://github.com/fluid-project/fluidproject.org/issues/15

**Comment by johntharian** [comment] 2020-03-15 14:17
May I solve this issue ?

**Comment by jobara** [comment] 2020-03-16 13:19
@johntharian we're still reviewing/discussing this issue. I don't think it's a good one to work on at this time.

**Comment by jhung** [comment] 2020-08-18 15:26
Closing. Duplicate of #172 .

**Closed by jhung** 2020-08-18 15:26 UTC
Labels: duplicate, question
