### ISSUE TITLE
images aligned to right in mobile view

### ISSUE THREAD

**Issue by Raunaksingh100** [fluid-project/floeproject.org#176] opened 2020-08-10 13:23 UTC
## Describe the bug
the all images are aligned to right not in center in the mobile view

### To reproduce
1. Go to 'https://floeproject.org/'
2. Scroll down to '....'
3. See error

### Expected behavior
image must be aligned in centre not to right

## Screenshots
![1img](https://user-images.githubusercontent.com/65535360/89787113-96094f00-db3a-11ea-9d1f-fc81c2011104.PNG)
![2img](https://user-images.githubusercontent.com/65535360/89787122-986ba900-db3a-11ea-8026-54d1719b0493.PNG)

### Smartphone / tablet 
 - Device: [e.g. iPhone6 , iphone5s, galxy fold , iphone6/7/8 plus]
 - Browser [e.g. stock browser]

**Comment by Raunaksingh100** [comment] 2020-08-10 13:23
### i am working on this issue ,,,,
thanks............

**Comment by colinbdclark** [comment] 2020-08-10 13:50
Hi @Raunaksingh100, thanks for filing this issue. We're in the midst of redesigning portions of the FLOE Website and migrating it to a static site generator, so now isn't a good time to be making styling changes to the existing site.

Also, I can't reproduce this issue on my on own device, so it seems likely that that further details about the environment are required. I noticed you didn't fill out the issue template for this. Next time, it would be helpful for you to include the details.

I'm going to go ahead and close this issue for now, and we can reopen it if it impacts the new version of the site then.

**Closed by colinbdclark** 2020-08-10 13:50 UTC

**Comment by Raunaksingh100** [comment] 2020-08-10 13:52
can you view my pr #176 i really fixed this issue

**Comment by colinbdclark** [comment] 2020-08-10 13:55
Hi @Raunaksingh100, please read my comments above. We can revisit this when the new site is launched.
