### ISSUE TITLE
Index page not responsive on mobile view

### ISSUE THREAD

**Issue by AsaoluElijah** [fluid-project/floeproject.org#153] opened 2020-03-25 00:08 UTC
## Describe the bug
Visiting the index page https://floeproject.org/ on a mobile device is not responsive

### To reproduce
1. Go to https://floeproject.org/ on a mobile device

## Screenshots
![Screenshot_20200325-005905](https://user-images.githubusercontent.com/34748637/77488186-c9219f00-6e34-11ea-82f4-84dfac55a274.png)

### Smartphone / tablet 
 - Device: Android
 - OS: Android 8.1
 - Browser Chrome
 - Version : 80.0.3987.132

**Comment by AsaoluElijah** [comment] 2020-03-25 00:09
And also, i'll like to work on this issue

**Comment by jobara** [comment] 2020-03-25 12:27
It appears that the issue isn't that the page isn't responsive, it's that there may be some bugs with the responsive styling. Please describe in detail what issues you are seeing. The screenshot shows only a small portion of the page and for those that cannot perceive the image there is no information about what the issue is. In fact I'm not sure from the image if the issue is only with the "show preferences" not expanding to the full width of the screen or if there is more.

**Comment by AsaoluElijah** [comment] 2020-03-25 18:07
Yeah, the issue is not only with the "show preferences" not expanding to the full width of the screen.
I'd noticed the page is non-responsive because of the **width** of the images on this page.
More screenshots below:
![Screenshot_20200325-190102](https://user-images.githubusercontent.com/34748637/77570154-9b3b6980-6ecb-11ea-9773-524a832daf53.png)
![Screenshot_20200325-190110](https://user-images.githubusercontent.com/34748637/77570198-a7bfc200-6ecb-11ea-92bb-f0e815dae0cf.png)
![Screenshot_20200325-190119](https://user-images.githubusercontent.com/34748637/77570226-b1e1c080-6ecb-11ea-84ae-407fb8598727.png)
![Screenshot_20200325-190135](https://user-images.githubusercontent.com/34748637/77570258-c02fdc80-6ecb-11ea-919f-d315b5f00149.png)

**Comment by jobara** [comment] 2020-03-26 11:52
The entire issue may be caused by the images forcing the width of the page to be too wide.

**Comment by AsaoluElijah** [comment] 2020-03-26 21:14
Exactly :+1: 
Thanks jobora, i'll submit a PR fixing this with css media query.

**Comment by thisispratt** [comment] 2020-03-27 07:44
Duplicate of #118

**Comment by jhung** [comment] 2020-08-18 17:28
Closing this issue. It will be addressed with #184 .

**Closed by jhung** 2020-08-18 17:28 UTC
Labels: duplicate
